#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Summarise data/boots.csv and fit the TSC warp against firmware time.

Writes data/warp-vs-firmware.csv (the points plotted in the report) and
prints the numbers the report quotes.

Usage: analyze.py [data/boots.csv]
"""
import csv
import os
import sys

TSC_HZ = 2.4953e9  # nominal TSC frequency of the Ryzen 9 8945HX

here = os.path.dirname(os.path.abspath(__file__))
src = sys.argv[1] if len(sys.argv) > 1 else os.path.join(here, "data", "boots.csv")
rows = list(csv.DictReader(open(src)))


def unfixed(r):
    # No tscsync, or tscsync in measure mode (which writes nothing).
    return r["tscsync"] == "" or r["tscsync"].endswith(" measure")


pre = [r for r in rows if unfixed(r)]
warp = [r for r in pre if r["warp_cycles"]]
points = [r for r in warp if r["firmware_s"]]
synced = [r for r in rows if not unfixed(r)]

print(f"boots in journal:        {len(rows)} ({rows[0]['date']} .. {rows[-1]['date']})")
print(f"unfixed boots:           {len(pre)}, with a warp line {len(warp)}")
print(f"  without a warp line:   {[(r['journal_boot'], r['date']) for r in pre if not r['warp_cycles']]}")
print(f"  warp, no firmware time: {len(warp) - len(points)} "
      f"(offline-update boots: {sum(1 for r in warp if not r['firmware_s'] and int(r['offline_update']))})")
print(f"  kernels:               {sorted({r['kernel'] for r in warp})}")
w = [int(r["warp_cycles"]) for r in warp]
print(f"  warp range:            {min(w)} .. {max(w)} cycles")

# Least-squares fit of warp against firmware time.
xs = [float(r["firmware_s"]) for r in points]
ys = [int(r["warp_cycles"]) for r in points]
n = len(xs)
mx, my = sum(xs) / n, sum(ys) / n
k = sum((a - mx) * (b - my) for a, b in zip(xs, ys)) / sum((a - mx) ** 2 for a in xs)
c = my - k * mx
res = [b - (k * a + c) for a, b in zip(xs, ys)]
r2 = 1 - sum(e * e for e in res) / sum((b - my) ** 2 for b in ys)
print(f"fit over {n} boots:       slope {k / 1e6:.2f} Mcycles/s, "
      f"intercept {c / TSC_HZ * 1e3:.2f} ms, R^2 {r2:.6f}, "
      f"largest miss {max(abs(e) for e in res) / TSC_HZ * 1e3:.2f} ms")
print(f"  slope / TSC rate:      {k / TSC_HZ:.4f} "
      f"(CPU 0 reads {1 / (1 + k / TSC_HZ):.4f} of the other cores' count)")

print(f"boots with tscsync sync: {len(synced)}, kept TSC {sum(int(r['tsc_kept']) > 0 for r in synced)}")
for r in synced:
    print(f"  {r['date']} {r['tscsync']:<12} warp={r['warp_cycles'] or '-':<4} kept={r['tsc_kept']}")

out = os.path.join(here, "data", "warp-vs-firmware.csv")
with open(out, "w") as f:
    f.write("firmware_s,warp_gcycles\n")
    for a, b in sorted(zip(xs, ys)):
        f.write(f"{a},{b / 1e9:.6f}\n")
with open(os.path.join(here, "data", "fit.tex"), "w") as f:
    f.write("% Generated by analyze.py\n")
    f.write(f"\\newcommand\\fitslope{{{k / 1e9:.5f}}}\n")
    f.write(f"\\newcommand\\fitpoints{{{n}}}\n")
print(f"wrote {out} and data/fit.tex")
